apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-consumer
spec:
  selector:
    matchLabels:
      app: mq-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: mq-consumer
    spec:
      containers:
        - name: mq-consumer
          image: catotv/mq-consumer
