on:
  push:
    branches: [development]

name: k8s-dev-deploy

jobs:
  deploy:
    name: k8s-dev-deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker-build-push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: catotv/mq-consumer:latest

      - name: Setup kubectl
        id: kubectl-setup
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: catotv-dev-cluster

      - name: Restart kubernetes deployment
        run: kubectl rollout restart deployment mq-consumer
